[package]
name = "service"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { workspace = true }
entity = { path = "../entity" }
anyhow = { workspace = true }
serde = { workspace = true }
