[package]
name = "service"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { workspace = true }
entity = { path = "../entity" }
serde = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
futures = "0.3.31"
