//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub mod prelude;

pub mod boss;
pub mod clothing;
pub mod procurement;
pub mod procurement_item;
pub mod production;
pub mod production_item;
pub mod shipment;
pub mod shipment_item;
pub mod staff;
pub mod user;
