//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub use super::boss::Entity as Boss;
pub use super::clothing::Entity as Clothing;
pub use super::procurement::Entity as Procurement;
pub use super::procurement_item::Entity as ProcurementItem;
pub use super::production::Entity as Production;
pub use super::production_item::Entity as ProductionItem;
pub use super::shipment::Entity as Shipment;
pub use super::shipment_item::Entity as ShipmentItem;
pub use super::staff::Entity as Staff;
pub use super::user::Entity as User;
