//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "production")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub description: Option<String>,
    pub create_at: DateTimeWithTimeZone,
    pub staff_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::production_item::Entity")]
    ProductionItem,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::StaffId",
        to = "super::staff::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::production_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductionItem.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
