//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "shipment_item")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub amount: i32,
    pub shipment_id: i32,
    pub clothing_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::clothing::Entity",
        from = "Column::ClothingId",
        to = "super::clothing::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Clothing,
    #[sea_orm(
        belongs_to = "super::shipment::Entity",
        from = "Column::ShipmentId",
        to = "super::shipment::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Shipment,
}

impl Related<super::clothing::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clothing.def()
    }
}

impl Related<super::shipment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Shipment.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
